// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlumpClient is the client API for Plump service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlumpClient interface {
	// Application-level functions
	CreateLock(ctx context.Context, in *CreateDestroyRequest, opts ...grpc.CallOption) (*CreateDestroyReply, error)
	DestroyLock(ctx context.Context, in *CreateDestroyRequest, opts ...grpc.CallOption) (*CreateDestroyReply, error)
	GetSequencer(ctx context.Context, in *SequencerRequest, opts ...grpc.CallOption) (*SequencerReply, error)
	GetLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error)
	LockKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error)
	ReleaseLock(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error)
	// Instrospection functions
	WhoHasLock(ctx context.Context, in *WhoHasRequest, opts ...grpc.CallOption) (*WhoHasReply, error)
	NextSequencer(ctx context.Context, in *NextSequencerRequest, opts ...grpc.CallOption) (*NextSequencerReply, error)
	ListLocks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
}

type plumpClient struct {
	cc grpc.ClientConnInterface
}

func NewPlumpClient(cc grpc.ClientConnInterface) PlumpClient {
	return &plumpClient{cc}
}

func (c *plumpClient) CreateLock(ctx context.Context, in *CreateDestroyRequest, opts ...grpc.CallOption) (*CreateDestroyReply, error) {
	out := new(CreateDestroyReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/CreateLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) DestroyLock(ctx context.Context, in *CreateDestroyRequest, opts ...grpc.CallOption) (*CreateDestroyReply, error) {
	out := new(CreateDestroyReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/DestroyLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) GetSequencer(ctx context.Context, in *SequencerRequest, opts ...grpc.CallOption) (*SequencerReply, error) {
	out := new(SequencerReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/GetSequencer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) GetLock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*LockReply, error) {
	out := new(LockReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/GetLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) LockKeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveReply, error) {
	out := new(KeepAliveReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/LockKeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) ReleaseLock(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error) {
	out := new(ReleaseReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/ReleaseLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) WhoHasLock(ctx context.Context, in *WhoHasRequest, opts ...grpc.CallOption) (*WhoHasReply, error) {
	out := new(WhoHasReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/WhoHasLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) NextSequencer(ctx context.Context, in *NextSequencerRequest, opts ...grpc.CallOption) (*NextSequencerReply, error) {
	out := new(NextSequencerReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/NextSequencer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plumpClient) ListLocks(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/plump.Plump/ListLocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlumpServer is the server API for Plump service.
// All implementations must embed UnimplementedPlumpServer
// for forward compatibility
type PlumpServer interface {
	// Application-level functions
	CreateLock(context.Context, *CreateDestroyRequest) (*CreateDestroyReply, error)
	DestroyLock(context.Context, *CreateDestroyRequest) (*CreateDestroyReply, error)
	GetSequencer(context.Context, *SequencerRequest) (*SequencerReply, error)
	GetLock(context.Context, *LockRequest) (*LockReply, error)
	LockKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveReply, error)
	ReleaseLock(context.Context, *ReleaseRequest) (*ReleaseReply, error)
	// Instrospection functions
	WhoHasLock(context.Context, *WhoHasRequest) (*WhoHasReply, error)
	NextSequencer(context.Context, *NextSequencerRequest) (*NextSequencerReply, error)
	ListLocks(context.Context, *ListRequest) (*ListReply, error)
	mustEmbedUnimplementedPlumpServer()
}

// UnimplementedPlumpServer must be embedded to have forward compatible implementations.
type UnimplementedPlumpServer struct {
}

func (UnimplementedPlumpServer) CreateLock(context.Context, *CreateDestroyRequest) (*CreateDestroyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLock not implemented")
}
func (UnimplementedPlumpServer) DestroyLock(context.Context, *CreateDestroyRequest) (*CreateDestroyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyLock not implemented")
}
func (UnimplementedPlumpServer) GetSequencer(context.Context, *SequencerRequest) (*SequencerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSequencer not implemented")
}
func (UnimplementedPlumpServer) GetLock(context.Context, *LockRequest) (*LockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLock not implemented")
}
func (UnimplementedPlumpServer) LockKeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockKeepAlive not implemented")
}
func (UnimplementedPlumpServer) ReleaseLock(context.Context, *ReleaseRequest) (*ReleaseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedPlumpServer) WhoHasLock(context.Context, *WhoHasRequest) (*WhoHasReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoHasLock not implemented")
}
func (UnimplementedPlumpServer) NextSequencer(context.Context, *NextSequencerRequest) (*NextSequencerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextSequencer not implemented")
}
func (UnimplementedPlumpServer) ListLocks(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocks not implemented")
}
func (UnimplementedPlumpServer) mustEmbedUnimplementedPlumpServer() {}

// UnsafePlumpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlumpServer will
// result in compilation errors.
type UnsafePlumpServer interface {
	mustEmbedUnimplementedPlumpServer()
}

func RegisterPlumpServer(s grpc.ServiceRegistrar, srv PlumpServer) {
	s.RegisterService(&Plump_ServiceDesc, srv)
}

func _Plump_CreateLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).CreateLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/CreateLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).CreateLock(ctx, req.(*CreateDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_DestroyLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).DestroyLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/DestroyLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).DestroyLock(ctx, req.(*CreateDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_GetSequencer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SequencerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).GetSequencer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/GetSequencer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).GetSequencer(ctx, req.(*SequencerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_GetLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).GetLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/GetLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).GetLock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_LockKeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).LockKeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/LockKeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).LockKeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/ReleaseLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).ReleaseLock(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_WhoHasLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoHasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).WhoHasLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/WhoHasLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).WhoHasLock(ctx, req.(*WhoHasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_NextSequencer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextSequencerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).NextSequencer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/NextSequencer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).NextSequencer(ctx, req.(*NextSequencerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plump_ListLocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlumpServer).ListLocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plump.Plump/ListLocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlumpServer).ListLocks(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plump_ServiceDesc is the grpc.ServiceDesc for Plump service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plump_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plump.Plump",
	HandlerType: (*PlumpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLock",
			Handler:    _Plump_CreateLock_Handler,
		},
		{
			MethodName: "DestroyLock",
			Handler:    _Plump_DestroyLock_Handler,
		},
		{
			MethodName: "GetSequencer",
			Handler:    _Plump_GetSequencer_Handler,
		},
		{
			MethodName: "GetLock",
			Handler:    _Plump_GetLock_Handler,
		},
		{
			MethodName: "LockKeepAlive",
			Handler:    _Plump_LockKeepAlive_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _Plump_ReleaseLock_Handler,
		},
		{
			MethodName: "WhoHasLock",
			Handler:    _Plump_WhoHasLock_Handler,
		},
		{
			MethodName: "NextSequencer",
			Handler:    _Plump_NextSequencer_Handler,
		},
		{
			MethodName: "ListLocks",
			Handler:    _Plump_ListLocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plump.proto",
}
